### PR TITLE
fix: add asterisk before username in CODEOWNERS file

### LINKED ISSUE #65: Bug: CODEOWNERS does not automatically add reviewers
## Describe the bug

Currently, we have CODEOWNERS file that contains the list of maintainers. But we don't get added automatically as reviewers as it suppposed to.

On [GitHub's docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners), it's also mentioned that if a file has a code owner, you can see who the code owner on the file. See example below:

Screenshot 2024-02-04 220339

But we don't have one, as shown in screenshot below.

Screenshot 2024-02-04 215517

### Suggested Solution

Looking at [the example on GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file), there is an asterisk added before team or username.

```text
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
*       @global-owner1 @global-owner2
```

Let's add this asterisk before all maintainers' name in the CODEOWNERS file.

## Expected behavior

CODEOWNERS suppose to automatically add people and/or team listed in the file as reviewers.

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR adds asterisk before username in CODEOWNERS file to fix maintainers not automatically added as reviewers.

### Note for maintainers:

As mentioned in [this comment](https://github.com/nickytonline/astro-partykit-starter/issues/24#issuecomment-1924684746), we need to merge this PR to test it out. In case it doesn't work, I will revert the merged PR.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #65 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

cross fingers gif

### CODE REVIEW

**Review by Satoshi-Sh — APPROVED** [review]
Thanks, @adiati98.  I hope this works out.

**Review by jdwilkin4 — APPROVED** [review]

**Comment by adiati98** [comment]
Thanks, @Satoshi-Sh @jdwilkin4!
Can anyone merge this PR? It's locked on my end. 😅

But also, I think maybe it has to do with the check of `Required statuses must pass before merging`. 🤔

cc: @nickytonline

**Comment by nickytonline** [comment]
> > Thanks, @Satoshi-Sh @jdwilkin4! Can anyone merge this PR? It's locked on my end. 😅
> 
> > 
> 
> > But also, I think maybe it has to do with the pending check of [`Required statuses must pass before merging`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks). 🤔
> 
> > 
> 
> > cc: @nickytonline
> 
> 
> 
> Hey @nickytonline,
> 
> 
> 
> I'm not sure what's going on with this pending check.
> 
> Jessica and Satoshi already approved this PR, but we can't merge it in because this test doesn't passed.

I had to approve the deploy preview. Should be done shortly.

**Comment by adiati98** [comment]
Thanks, @nickytonline!
Now I see that all files has the symbol that point that they are belong to CODEOWNERS. 
However, all are only owned by Teri. 😅

Screenshot 2024-02-15 162947

Let me create a dummy PR that I will close it later to test. 👍

**Comment by adiati98** [comment]
@nickytonline okay, this seems works. Previously, we have to add reviewers manually.
Now, Teri is automatically added as reviewer.

Screenshot 2024-02-15 164018

---

I followed the format as in CODEOWNERS at VC.
But looking at the docs, I think we need to write the owners inline as below screenshot.

Screenshot 2024-02-15 164434

Let me create a new PR for this. If it doesn't work as well, then I don't have any other idea for now😅

**PS**: If this works, I want to apply it at OpenSauced's Community repos as the team is also not automatically be added as reviewers there 😁

**Pull request merged**
