### PR TITLE
Update README.md

### LINKED ISSUE #201: Wrong partykit cli url
## Describe the bug

Wrong partykit cli url.

#200 fixes that..

### PR DESCRIPTION
**Pull request by millette**
## Description

Update partykit cli url.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #201

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Thanks for the PR @millette! Mind creating a short issue for this to link to the PR?

**Comment by millette** [comment]
@nickytonline Sure, I just did. But why was it needed?

**Comment by nickytonline** [comment]
> @nickytonline Sure, I just did. But why was it needed?

Most projects I work on begin with an issue.

**Comment by nickytonline** [comment]
@adiati98, when you have a chance, mind giving this a review?

**Review by adiati98 — APPROVED** [review]
Hey @millette,

Sorry for the late response.
Thanks for fixing the URL! ✨ 🚢

**Pull request merged**
