### PR TITLE
fix: format codeowners

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR fixes the format in CODEOWNERS file to be inline.

See [this comment](https://github.com/nickytonline/astro-partykit-starter/pull/66#issuecomment-1946376422) for the background.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

- Relates to #65 
- Fixes #66 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by Satoshi-Sh — APPROVED** [review]
Looks good to me.

**Review by nickytonline — APPROVED** [review]

**Comment by adiati98** [comment]
Hmm... There are 2 approvals already, but we still can't merge this in. 🤔

**Comment by Satoshi-Sh** [comment]
Screenshot from 2024-02-15 13-31-13
We might need the code owner's approval. For some reason, Terieyenike is the only one.

**Comment by nickytonline** [comment]
I'll go ahead and merge as an admin an hopefully the CODEOWNERS is in a good state now.

**Comment by adiati98** [comment]
It works!!! 🎉
Thanks for the merge, @nickytonline!

 
Screenshot 2024-02-15 221608

Screenshot 2024-02-15 222124

**Pull request merged**
