### PR TITLE
Bug Fix: add unique keys

### PR DESCRIPTION
**Pull request by Arol15**
## Description

This PR replaces non-unique keys with stable unique keys by using `crypto.randomUUID` as recommended in the official React docs: https://react.dev/learn/rendering-lists#where-to-get-your-key. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes https://github.com/nickytonline/astro-partykit-starter/issues/32

## Mobile & Desktop Screenshots/Recordings

app with messages and console logs

## Steps to QA

1. Go to the chat room.
2. Send duplicated messages.
3. Open the browser's dev tools, navigate to `Console` tab and make sure you don't see any warnings. 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Noticed potential improvements: 

- clear the input field after a message has been successfully posted; 
- fix TS warning for this line: `const text = form.get("message").valueOf();` - text can be null; 
- make input field required or disable `send message` button if no input entered; 

## [optional] What gif best describes this PR or how it makes you feel?

gif

### CODE REVIEW

**Review by Satoshi-Sh — APPROVED** [review]
Looks great to me. Thanks for sharing the React doc link too. 

Your 3 suggestions are valid as well. We can make new issues. What do you think, @nickytonline ?

**Review by jdwilkin4 — APPROVED** [review]
LGTM 👍

**Comment by Arol15** [comment]
@Satoshi-Sh @jdwilkin4 do you know if there is anything I need to do to get `deploy/netlify` check to pass?

**Comment by nickytonline** [comment]
> @Satoshi-Sh @jdwilkin4 do you know if there is anything I need to do to get `deploy/netlify` check to pass? 

I need to approve it. I'll go ahead and run it.

**Pull request merged**
